@url=http://localhost:3000

GET {{url}}/materias

### Consultar por una materia
GET {{url}}/materias/2

### Crear materia
POST {{url}}/materias
Content-Type: application/json

{
    "nombre":"Bioquimica",
    "año": "2025",
    "codigo": "4887569"
}

### Modificar materia 
PUT {{url}}/materias/3
Content-Type: application/json

{
    "nombre":"Biologia",
    "año": "2024",
    "codigo": "1234567"
}

### Eliminar materia
DELETE {{url}}/materias/4