@url=http://localhost:3000

### consultar todas las notas
GET {{url}}/notas

### Consultar notas
GET {{url}}/notas/alumnos/1/materias/2

### Poner notas
POST {{url}}/notas/alumnos/1/materias/3
Content-Type: application/json

{
    "nota1": 8,
    "nota2": 9,
    "nota3": 10
}

### Modificar notas
PUT {{url}}/notas/alumnos/2/materias/2
Content-Type: application/json

{
    "nota1": 10,
    "nota2": 10,
    "nota3": 10
}